[supervisord]
logfile=supervisord.log ; Fichier de log principal de supervisor
pidfile=supervisord.pid ; Stocke le PID de supervisor
nodaemon=false          ; Tourne en tâche de fond (background)

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; Socket de communication

[unix_http_server]
file=/tmp/supervisor.sock   

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# -----------------------------------------------------
# NOTRE APPLICATION À SURVEILLER (Le cœur du test)
# -----------------------------------------------------
[program:mon_worker]
command=./worker.sh              ; La commande qu'on vient de créer
directory=%(here)s               ; S'exécute dans le dossier actuel
autostart=true                   ; Se lance automatiquement au démarrage
autorestart=unexpected           ; Ne redémarre QUE si le crash est anormal
exitcodes=0,2                    ; Codes de sortie considérés comme "normaux"
startretries=3                   ; Nombre d'essais max si crash au démarrage
starttime=5                      ; Doit tenir 5s pour être considéré "UP"
stopsignal=TERM                  ; Signal envoyé pour un arrêt propre (SIGTERM)
stopwaitsecs=5                   ; Attend 5s avant de forcer un kill -9
stdout_logfile=worker.stdout.log ; Redirection du stdout
stderr_logfile=worker.stderr.log ; Redirection du stderr
