programs:
  my_worker:
    cmd: "./scripts/worker.sh"         
    numprocs: 1
    autostart: true
    autorestart: "unexpected"
    exitcodes:
      - 0
      - 2
    starttime: 5
    startretries: 3
    stopsignal: "TERM"
    stoptime: 5
    stdout: "./logs/worker.stdout.log" 
    stderr: "./logs/worker.stderr.log"
    workingdir: ""
    umask: "022"
    env:                               
      ENV_VAR: "production"
      DEBUG: "false"

  my_worker2:
    cmd: "./scripts/worker.sh"
    numprocs: 2
    autostart: false                   
    autorestart: "unexpected"
    exitcodes:
      - 0
      - 2
    starttime: 5
    startretries: 3
    stopsignal: "KILL"
    stoptime: 5
    stdout: "./logs/worker2.stdout.log"
    stderr: "./logs/worker2.stderr.log"
    workingdir: ""
    umask: "022"